
function getIconsFontAwesome() {
    return '<option value="address-book">address-book</option>' +
    '<option value="address-card">address-card</option>' +
    '<option value="angry">angry</option>' +
    '<option value="arrow-alt-circle-down">arrow-alt-circle-down</option>' +
    '<option value="arrow-alt-circle-left">arrow-alt-circle-left</option>' +
    '<option value="arrow-alt-circle-right">arrow-alt-circle-right</option>' +
    '<option value="arrow-alt-circle-up">arrow-alt-circle-up</option>' +
    '<option value="bell">bell</option>' +
    '<option value="bell-slash">bell-slash</option>' +
    '<option value="bookmark">bookmark</option>' +
    '<option value="building">building</option>' +
    '<option value="calendar">calendar</option>' +
    '<option value="calendar-alt">calendar-alt</option>' +
    '<option value="calendar-check">calendar-check</option>' +
    '<option value="calendar-minus">calendar-minus</option>' +
    '<option value="calendar-plus">calendar-plus</option>' +
    '<option value="calendar-times">calendar-times</option>' +
    '<option value="caret-square-down">caret-square-down</option>' +
    '<option value="caret-square-left">caret-square-left</option>' +
    '<option value="caret-square-right">caret-square-right</option>' +
    '<option value="caret-square-up">caret-square-up</option>' +
    '<option value="chart-bar">chart-bar</option>' +
    '<option value="check-circle">check-circle</option>' +
    '<option value="check-square">check-square</option>' +
    '<option value="circle">circle</option>' +
    '<option value="clipboard">clipboard</option>' +
    '<option value="clock">clock</option>' +
    '<option value="clone">clone</option>' +
    '<option value="closed-captioning">closed-captioning</option>' +
    '<option value="comment">comment</option>' +
    '<option value="comment-alt">comment-alt</option>' +
    '<option value="comment-dots">comment-dots</option>' +
    '<option value="comments">comments</option>' +
    '<option value="compass">compass</option>' +
    '<option value="copy">copy</option>' +
    '<option value="copyright">copyright</option>' +
    '<option value="credit-card">credit-card</option>' +
    '<option value="dizzy">dizzy</option>' +
    '<option value="dot-circle">dot-circle</option>' +
    '<option value="edit">edit</option>' +
    '<option value="envelope">envelope </option>' +
    '<option value="envelope-open">envelope-open</option>' +
    '<option value="eye">eye</option>' +
    '<option value="eye-slash">eye-slash</option>' +
    '<option value="file">file</option>' +
    '<option value="file-alt">file-alt</option>' +
    '<option value="file-archive">file-archive</option>' +
    '<option value="file-audio">file-audio</option>' +
    '<option value="file-code">file-code</option>' +
    '<option value="file-excel">file-excel </option>' +
    '<option value="file-image">file-image</option>' +
    '<option value="file-pdf">file-pdf</option>' +
    '<option value="file-powerpoint">file-powerpoint</option>' +
    '<option value="file-video">file-video</option>' +
    '<option value="file-word">file-word</option>' +
    '<option value="flag">flag</option>' +
    '<option value="flushed">flushed</option>' +
    '<option value="folder">folder</option>' +
    '<option value="folder-open">folder-open </option>' +
    '<option value="frown">frown</option>' +
    '<option value="frown-open">frown-open</option>' +
    '<option value="futbol">futbol</option>' +
    '<option value="gem">gem</option>' +
    '<option value="grimace">grimace</option>' +
    '<option value="grin">grin</option>' +
    '<option value="grin-alt">grin-alt</option>' +
    '<option value="grin-beam">grin-beam</option>' +
    '<option value="grin-beam-sweet">grin-beam-sweet </option>' +
    '<option value="grin-hearts">grin-hearts</option>' +
    '<option value="grin-squint">grin-squint</option>' +
    '<option value="grin-squint-tears">grin-squint-tears</option>' +
    '<option value="grin-stars">grin-stars</option>' +
    '<option value="grin-tears">grin-tears</option>' +
    '<option value="grin-tongue">grin-tongue</option>' +
    '<option value="grin-tongue-squint">grin-tongue-squint</option>' +
    '<option value="grin-tongue-wink">grin-tongue-wink</option>' +
    '<option value="grin-wink">grin-wink </option>' +
    '<option value="hand-lizard">hand-lizard</option>' +
    '<option value="hand-paper">hand-paper</option>' +
    '<option value="hand-peace">hand-peace</option>' +
    '<option value="hand-point-down">hand-point-down</option>' +
    '<option value="hand-point-left">hand-point-left</option>' +
    '<option value="hand-point-right">hand-point-right</option>' +
    '<option value="hand-point-up">hand-point-up</option>' +
    '<option value="hand-pointer">hand-pointer</option>' +
    '<option value="hand-rock">hand-rock </option>' +
    '<option value="hand-scissors">hand-scissors</option>' +
    '<option value="hand-spock">hand-spock</option>' +
    '<option value="handshake">handshake</option>' +
    '<option value="hdd">hdd</option>' +
    '<option value="heart">heart</option>' +
    '<option value="home">home</option>' +
    '<option value="hospital">hospital</option>' +
    '<option value="hourglass">hourglass</option>' +
    '<option value="id-badge">id-badge</option>' +
    '<option value="id-card">id-card </option>' +
    '<option value="image">image</option>' +
    '<option value="images">images</option>' +
    '<option value="keyboard">keyboard</option>' +
    '<option value="kiss">kiss</option>' +
    '<option value="kiss-beam">kiss-beam</option>' +
    '<option value="kiss-wink-heart">kiss-wink-heart</option>' +
    '<option value="laugh">laugh</option>' +
    '<option value="laugh-beam">laugh-beam</option>' +
    '<option value="laugh-squint">laugh-squint </option>' +
    '<option value="laugh-wink">laugh-wink</option>' +
    '<option value="lemon">lemon</option>' +
    '<option value="life-ring">life-ring</option>' +
    '<option value="lightbulb">lightbulb</option>' +
    '<option value="list-alt">list-alt</option>' +
    '<option value="map">map</option>' +
    '<option value="meh">meh</option>' +
    '<option value="meh-blank">meh-blank</option>' +
    '<option value="meh-rolling-eyes">meh-rolling-eyes </option>' +
    '<option value="minus-square">minus-square</option>' +
    '<option value="money-bill-alt">money-bill-alt</option>' +
    '<option value="moon">moon</option>' +
    '<option value="newspaper">newspaper</option>' +
    '<option value="object-group">object-group</option>' +
    '<option value="object-upgroup">object-upgroup</option>' +
    '<option value="paper-plane">paper-plane</option>' +
    '<option value="pause-circle">pause-circle</option>' +
    '<option value="play-circle">play-circle </option>' +
    '<option value="plus-square">plus-square</option>' +
    '<option value="question-circle">question-circle</option>' +
    '<option value="registered">registered</option>' +
    '<option value="sad-cry">sad-cry</option>' +
    '<option value="sad-tear">sad-tear</option>' +
    '<option value="save">save</option>' +
    '<option value="share-square">share-square</option>' +
    '<option value="smile">smile</option>' +
    '<option value="smile-beam">smile-beam </option>' +
    '<option value="smile-wink">smile-wink</option>' +
    '<option value="snowflake">snowflake</option>' +
    '<option value="square">square</option>' +
    '<option value="star">star</option>' +
    '<option value="star-half">star-half</option>' +
    '<option value="sticky-note">sticky-note</option>' +
    '<option value="stop-circle">stop-circle</option>' +
    '<option value="sun">sun</option>' +
    '<option value="surprise">surprise </option>' +
    '<option value="thumbs-down">thumbs-down</option>' +
    '<option value="thumbs-up"> thumbs-up</option>' +
    '<option value="times-circle">times-circle</option>' +
    '<option value="tired">tired</option>' +
    '<option value="trash-alt">trash-alt</option>' +
    '<option value="user">user</option>' +
    '<option value="user-circle">user-circle</option>' +
    '<option value="window-close">window-close</option>' +
    '<option value="window-maximize">window-maximize </option>' +
    '<option value="window-minimize">window-minimize</option>' +
    '<option value="window-restore">window-restore</option>';
}